[package]
name = "efd"
description = "Elliptical Fourier Descriptor (EFD) curve fitting in Rust."
version = "0.2.0"
authors = ["KmolYuan <pyslvs@gmail.com>"]
edition = "2018"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/KmolYuan/efd-rs"
keywords = ["efd", "elliptical", "fourier-descriptor", "algorithm"]

[dependencies]
ndarray = "0.15.1"
