[package]
name = "efd"
description = "Elliptical Fourier Descriptor (EFD) implementation in Rust."
version = "0.6.0"
authors = ["KmolYuan <pyslvs@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/KmolYuan/efd-rs"
keywords = ["efd", "elliptical", "fourier-descriptor", "algorithm"]

[dependencies]
ndarray = "0.15"
