[package]
name = "efd"
description = "Elliptical Fourier Descriptor (EFD) implementation in Rust."
version = "0.16.2"
authors = ["KmolYuan <pyslvs@gmail.com>"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/KmolYuan/efd-rs"
keywords = ["efd", "elliptical", "fourier-descriptor", "algorithm"]
categories = ["algorithm", "no-std"]

[features]
default = ["std"]
std = ["num-traits/std", "ndarray/std"]

[dependencies]
num-traits = { version = "0.2", default-features = false, features = ["libm"] }
ndarray = { version = "0.15", default-features = false }
